### ISSUE TITLE
org-similarity read path from cache instead of `org-roam-directory`

### ISSUE THREAD

**Issue by suliveevil** [brunoarine/org-similarity#9]
I moved files to `~/test` folder, but org-similarity didn't follow `org-roam-directory`

https://github.com/suliveevil/test

```python
ValueError: '/Users/suliveevil/org-roam/reference/stay_hungry_stay_foolish.org' is not in the subpath of '/Users/suliveevil/test' OR one path is relative and the other is absolute.
```

<img width="1552" alt="org-similarity-path" src="https://user-images.githubusercontent.com/35763237/209679821-cb90f27c-dee5-4451-99fd-f36d8fa93a67.png">

full output

```python
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/suliveevil/.config/emacs/lib/org-similarity/venv/lib/python3.10/site-packages/orgsimilarity/__main__.py", line 257, in <module>
    main()
  File "/Users/suliveevil/.config/emacs/lib/org-similarity/venv/lib/python3.10/site-packages/orgsimilarity/__main__.py", line 243, in main
    results = format_results(
  File "/Users/suliveevil/.config/emacs/lib/org-similarity/venv/lib/python3.10/site-packages/orgsimilarity/__main__.py", line 214, in format_results
    target_rel_path = target.relative_to(input_path.parent)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/Users/suliveevil/org-roam/reference/stay_hungry_stay_foolish.org' is not in the subpath of '/Users/suliveevil/test' OR one path is relative and the other is absolute.
```

**Comment by suliveevil** [comment]
I reboot my device, error remains.

**Comment by brunoarine** [comment]
I'm not sure if that's the root of the problem, but seems there's an issue with how the code is inferring relative paths. I have merged a PR (#10), let me know if it works now.

Also, could you please check if your `org-similarity-directory` variable is indeed pointing to the wrong path? Make sure to `(setq org-similarity-directory org-roam-directory)` after `org-similarity` has been loaded as well, if you haven't done so.

**Comment by suliveevil** [comment]
org-roam-directory follows my `.dic-locals.el` setting while org-similarity didn't.

```emacs-lisp
((nil . ((eval . (setq-local
                  org-roam-directory (expand-file-name (locate-dominating-file
                                                        default-directory ".dir-locals.el"))))
         (eval . (setq-local
                  org-roam-db-location (expand-file-name "org-roam.db"
                                                         org-roam-directory))))))
```

**Comment by brunoarine** [comment]
Now I see. If you set `org-similarity-directory`'s value with `setq`, it will get the same value as `org-directory` (or `org-roam-directory`) at the moment you evaluated the command. Any changes to the latter will not be reflected onto the former indeed. Example:

```lisp
(setq org-roam-directory "~/original/path")
(setq org-similarity-directory org-roam-directory)
(message org-similarity-directory)  ;; "~/original/path"

(setq org-roam-directory "~/new/path")
(message org-similarity-directory)  ;; "~/original/path"
```

If you wish that `org-similarity-directory` have the same value as `org-directory` or `org-roam-directory`, you should use variable aliasing. Example:

```lisp
(setq org-roam-directory "~/original/path")
(defvaralias 'org-similarity-directory 'org-roam-directory)
(setq org-roam-directory "~/new/path")
(message org-similarity-directory)  ;; "~/new/path"
```

**Comment by suliveevil** [comment]
Wow, this is great, and how can I ignore the defvaralias warning? Thank you very much.

```emacs-lisp
⛔ Warning (defvaralias): Overwriting value of ‘org-similarity-directory’ by aliasing to ‘org-roam-directory’
```

I opened a file and get another error 🤣:

```emacs-lisp
ValueError: '/Users/suliveevil/org-roam/topics/go.org' is not in the subpath of '/Users/suliveevil/org-roam/Emacs/package' OR one path is relative and the other is absolute.
```

<img width="1552" alt="截屏2022-12-28 00 56 02" src="https://user-images.githubusercontent.com/35763237/209697721-3a0f56f3-c8a8-44f6-84aa-e9c3ce7bdee5.png">

full output:

```emacs-lisp
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/suliveevil/.config/emacs/lib/org-similarity/venv/lib/python3.10/site-packages/orgsimilarity/__main__.py", line 257, in <module>
    main()
  File "/Users/suliveevil/.config/emacs/lib/org-similarity/venv/lib/python3.10/site-packages/orgsimilarity/__main__.py", line 243, in main
    results = format_results(
  File "/Users/suliveevil/.config/emacs/lib/org-similarity/venv/lib/python3.10/site-packages/orgsimilarity/__main__.py", line 214, in format_results
    target_rel_path = target.relative_to(input_path.parent)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/Users/suliveevil/org-roam/topics/go.org' is not in the subpath of '/Users/suliveevil/org-roam/Emacs/package' OR one path is relative and the other is absolute.
```

**Comment by suliveevil** [comment]
the latest commit fixed this issue. You are amazing!
